### ISSUE TITLE
Step 4 and 5

### ISSUE THREAD

**Issue by jennirpf** [raspberrypilearning/scary-spot-the-difference-scratch#5]
Hi!
Sorry if I have misunderstood, but I wondered if the blocks should be in the following order:

when green flag clicked
forever
switch backdrop to (start v)
if <mouse down?> then
+wait (pick random (0) to (10)) seconds
+switch backdrop to (scare v)
end
end

rather than
+wait (pick random (0) to (10)) seconds
+switch backdrop to (scare v)
being the other way around.

As I understand it, if 'switch' comes straight after the click and before 'wait', the backdrop will change as soon as the user clicks, rather than after a random pause.

Thank you!

**Comment by MarcScott** [comment]
Yes, they should. Thanks for spotting that - I'll change and then push to master.
